### ISSUE TITLE
gt readjoiner spmtest: error

### ISSUE THREAD

**Issue by hackerzone85** [chengyuan/reago#3]
``` javascript
blab@blab:~/Downloads/reago-1.1$ python reago.py filter_out/filtered.fasta sample_out -l 101
Sat Oct 17 16:14:49 2015 REAGO (v1.10) started...
Input file: filter_out/filtered.fasta
Parameters:
-e 0.05
-f 1350
-b 10
-l 101.0
-o 0.7
-t 30
Sat Oct 17 16:14:49 2015 Reading input file...
Sat Oct 17 16:14:49 2015 Initializing overlap graph...
gt readjoiner spmtest: error: fopen(): cannot open file 'sample_out/rj/graph.set.0.spm': No such file or directory
Traceback (most recent call last):
  File "reago.py", line 816, in <module>
    G = create_graph_using_rj(read_db, "graph")
  File "reago.py", line 110, in create_graph_using_rj
    f = open(output_dir + "/rj/" + graph_fn + ".set.des")
IOError: [Errno 2] No such file or directory: 'sample_out//rj/graph.set.des'
```

**Comment by microbiaki** [comment]
Hello hackerzone85,
did you manage to resolve the issue? I am getting the same error with reago1.1

Thank you,
Maria

**Comment by hackerzone85** [comment]
Let me try, if success then i reply with solution

On Sat, Jan 23, 2016 at 2:39 AM, mpachiad notifications@github.com wrote:

> Hello hackerzone85,
> did you manage to resolve the issue? I am getting the same error with
> reago1.1
> 
> Thank you,
> Maria
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chengyuan/reago/issues/3#issuecomment-174049509.

## 

Mahendra Gaur (M.Tech Bioinformatics, GBU, NOIDA)
Project Assistant
Biomics & Biodiversity Lab
Centre of Biotechnology
Siksha ‘O’ Anusandhan University
Kalinga Nagar, Ghatikia
Bhubaneswar-751003
E-Mail.-mahendra.gbu@gmail.com (primary)
           mahi61285@gmail.com
Mob. :- +91-9583630937 (BBSR)
           +91-9694157484 (Kota)
           +91-7683986167 (BBSR)

_RG Profile:_ https://www.researchgate.net/profile/Mahendra_Gaur4

**Comment by baibingbingbai** [comment]
Hello hackerzone85,
did you manage to resolve the issue? I am getting the same error with reago1.1

Thank you,
bingbai
