### ISSUE TITLE
filtered_input.py aborts with KeyError

### ISSUE THREAD

**Issue by jvollme** [chengyuan/reago#4]
Hello,
I am trying to run Reago v.1.1 on a set of metagenomes. But the "filter_input" step aborts after identifying only two 16S reads ( I know there are lots more from using Emirge and from preliminary metagenome assemblies).
The error message is:

> Traceback (most recent call last):
>   File "/home/jov14/tools/reago-1.1/filter_input.py", line 171, in <module>
>     seq_1 = db_1[read_id_1]
> KeyError: 'M03384:20:000000000-AF6R5:1:1118:5599:7547'

My program call was this (input is read from temporary files, because i have to convert my fastq files to fasta for reago):
`python filter_input.py /tmp/543367.1.masterqueue.q/tmp.qB7dZ8x8RPkelpa_1.fasta /tmp/543367.1.masterqueue.q/tmp.yZngfVXYQTkelpa_2.fasta ./kelpa /home/jov14/tools/reago-1.1/cm ba 8
`
My OS is Red Hat Enterprise Linux Server release 7.2 (Maipo).
I have Infernal v1.1.1 and Genometools v.1.5.8 installed.

**Comment by 05011996** [comment]
Hai,
I try to run the command
python filter_input.py ERR414251_1.fasta ERR414251_2.fasta filter_out cm ba 10 
and I get the following error 
python: can't open file 'filter_input.py': [Errno 2] No such file or directory
I download reago from github (https://github.com/chengyuan/reago-1.1) 
Install using conda, it fist show error in installation.
UnsatisfiableError: The following specifications were found to be in conflict:
  - reago
  - secretstorage
Use "conda info <package>" to see the dependencies for each package.

 I create a new conda environment for avoiding the error.
conda create -n reago reago
 The installation succeeds after creating a new environment but command is not working for my data.

**Comment by Leitemfa** [comment]
Hi,

I also found the same error when running filter_input.py, see below:

`Traceback (most recent call last):
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/binningMarcio/shotgun-workflow-MiSeq/analysis/.snakemake/conda/be0a5744/bin/filter_input.py", line 173, in <module>
    seq_1 = db_1[read_id_1]
KeyError: 'M00833:599:000000000-BFN38:1:1105:5905:15364'
`
